[tool.poetry]
name = "probability-calc"
version = "0.1.0"
description = ""
authors = ["dtzz81 <denise.turkova@madetech.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
